[package]
description = "Interact with unix processes/bash the same way as pexpect or Don libes expect does"
name        = "rexpect"
version     = "0.5.0"
authors     = ["Philipp Keller <philipp.keller@gmail.com>"]
edition     = "2021"
repository  = "https://github.com/rust-cli/rexpect"
homepage    = "https://github.com/rust-cli/rexpect"
license     = "MIT"
categories  = ["os::unix-apis"]
keywords    = ["pty", "automation", "testing", "expect", "pexpect"]
readme      = "README.md"
rust-version = "1.60"

[dependencies]
comma = "1.0"
libc = "0.2.147"
mio = { version = "0.8.8", features = ["os-poll", "os-ext"] }
nix = "0.26"
regex = "1"
signal-hook = "0.3.17"
tempfile = "3"
thiserror = "1.0.34"

which = { version = "4.4", optional = true }

[badges]
maintenance = { status = "passively-maintained" }

[features]
default = []
which = ["dep:which"]
